package com.dhcs.userinterface.role.doctor;


import com.dhcs.business.doctor.Doctor;
import com.dhcs.business.enterprise.Enterprise;
import com.dhcs.business.organization.DoctorOrganization;
import com.dhcs.business.useraccount.UserAccount;
import com.dhcs.business.workqueue.HospitalWorkRequest;
import com.dhcs.business.workqueue.LabTestWorkRequest;
import com.dhcs.business.workqueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;
/**
 *
 * @author shivesh
 */
public class DoctorWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private DoctorOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private static final Logger logger = Logger.getLogger(DoctorWorkAreaJPanel.class);
    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public DoctorWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, 
            DoctorOrganization organization, Enterprise enterprise) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(  
          "Bookman Old Style", Font.BOLD, 18)));  
        populateRequestTable();
        workRequestFromHosJTable.removeColumn(workRequestFromHosJTable.getColumnModel().getColumn(0));
        workRequestFromHosJTable.getTableHeader().setFont(new Font("MS Reference Sans Serif", Font.BOLD, 18));
        populateHospitalRequestTable();
    }
    
     private void populateHospitalRequestTable() {
          DefaultTableModel model = (DefaultTableModel) workRequestFromHosJTable.getModel();
        
        model.setRowCount(0);
        Doctor doc = (Doctor)userAccount.getEmployee();
        for (WorkRequest request : doc.getWorkQueue().getWorkRequestList()){
            HospitalWorkRequest  hospitalWorkRequest = (HospitalWorkRequest)request;
            Object[] row = new Object[3];
            //TODO row
            row[0] = hospitalWorkRequest;
            row[1] = hospitalWorkRequest.getHospitalName();
            row[2] = hospitalWorkRequest.getDoctorStatus();
            
            model.addRow(row);
        }
       
    }
     
    public void populateRequestTable(){
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();
        
        model.setRowCount(0);
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[4];
            row[0] = request.getMessage();
            row[1] = request.getReceiver();
            row[2] = request.getStatus();
            String result = ((LabTestWorkRequest) request).getTestResult();
            row[3] = result == null ? "Waiting" : result;
            
            model.addRow(row);
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        requestTestJButton = new javax.swing.JButton();
        refreshTestJButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        workRequestFromHosJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        docReqProcessjButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        workRequestJTable.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 16)); // NOI18N
        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Message", "Receiver", "Status", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        workRequestJTable.setRowHeight(25);
        jScrollPane1.setViewportView(workRequestJTable);
        if (workRequestJTable.getColumnModel().getColumnCount() > 0) {
            workRequestJTable.getColumnModel().getColumn(0).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(1).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(2).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(3).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 670, 950, 160));

        requestTestJButton.setBackground(new java.awt.Color(204, 0, 0));
        requestTestJButton.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 24)); // NOI18N
        requestTestJButton.setText("Request Test");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });
        add(requestTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 860, 300, 60));

        refreshTestJButton.setBackground(new java.awt.Color(33, 105, 33));
        refreshTestJButton.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 20)); // NOI18N
        refreshTestJButton.setText("Refresh");
        refreshTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTestJButtonActionPerformed(evt);
            }
        });
        add(refreshTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 620, 160, 40));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        workRequestFromHosJTable.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 16)); // NOI18N
        workRequestFromHosJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Request Object", "Hospital Name", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        workRequestFromHosJTable.setRowHeight(25);
        jScrollPane2.setViewportView(workRequestFromHosJTable);
        if (workRequestFromHosJTable.getColumnModel().getColumnCount() > 0) {
            workRequestFromHosJTable.getColumnModel().getColumn(0).setResizable(false);
            workRequestFromHosJTable.getColumnModel().getColumn(1).setResizable(false);
            workRequestFromHosJTable.getColumnModel().getColumn(2).setResizable(false);
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 950, 160));

        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 20)); // NOI18N
        jLabel1.setText("Request Received");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 210, 39));

        docReqProcessjButton.setBackground(new java.awt.Color(0, 153, 51));
        docReqProcessjButton.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 24)); // NOI18N
        docReqProcessjButton.setText("Process");
        docReqProcessjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docReqProcessjButtonActionPerformed(evt);
            }
        });
        add(docReqProcessjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 450, 300, 60));

        jLabel5.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 45)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Doctor Work Area");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0), 3));
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 630, 90));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/dhcs/util/image/doctor-panel.jpg"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1700, 1000));
    }// </editor-fold>//GEN-END:initComponents

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed
        
        int selectedRow = workRequestFromHosJTable.getSelectedRow();
        if (selectedRow < 0) {
             JOptionPane.showMessageDialog(this, "Please select a request for lab test  ",
                           "Decentralised Health Care System",JOptionPane.WARNING_MESSAGE);
            return;
        }
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("RequestLabTestJPanel", new RequestLabTestJPanel(userProcessContainer, userAccount, enterprise));
        layout.next(userProcessContainer);
        logger.info("Doctor Requested for test"+userAccount.getUsername());
        
    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void refreshTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTestJButtonActionPerformed

        populateRequestTable();
        
    }//GEN-LAST:event_refreshTestJButtonActionPerformed

    private void docReqProcessjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docReqProcessjButtonActionPerformed
      
        int selectedRow = workRequestFromHosJTable.getSelectedRow();

        if (selectedRow < 0) {
             JOptionPane.showMessageDialog(this, "Please select a request to process  ",
                           "Decentralised Health Care System",JOptionPane.WARNING_MESSAGE);
            return;
        }

        HospitalWorkRequest request = (HospitalWorkRequest) workRequestFromHosJTable.getModel().getValueAt(selectedRow, 0);
        request.setDoctorStatus("Request Accepted");
        request.setHospitalStatus("Request Processed");
        request.setStatus("Doctor Assigned");
        request.setDoctor((Doctor)userAccount.getEmployee());
        
        populateHospitalRequestTable();
    }//GEN-LAST:event_docReqProcessjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton docReqProcessjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton refreshTestJButton;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JTable workRequestFromHosJTable;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables

   
}
