/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dhcs.userinterface.role.doctor;

import com.dhcs.business.doctor.Doctor;
import com.dhcs.business.enterprise.Enterprise;
import com.dhcs.business.organization.LabOrganization;
import com.dhcs.business.organization.Organization;
import com.dhcs.business.useraccount.UserAccount;
import com.dhcs.business.workqueue.LabTestWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Font;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import org.apache.log4j.Logger;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;


/**
 *
 * @author raunak
 */
public class RequestLabTestJPanel extends javax.swing.JPanel {
    private static final Logger logger = Logger.getLogger(RequestLabTestJPanel.class);
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    /**
     * Creates new form RequestLabTestJPanel
     */
    public RequestLabTestJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(  
          "Bookman Old Style", Font.BOLD, 18)));  
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rbcCheckBox = new javax.swing.JCheckBox();
        glCheckBox = new javax.swing.JCheckBox();
        triCheckBox = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        proCheckBox = new javax.swing.JCheckBox();
        choCheckBox = new javax.swing.JCheckBox();
        sugarCheckBox = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        diaCheckBox = new javax.swing.JCheckBox();
        nauCheckBox = new javax.swing.JCheckBox();
        fatCheckBox = new javax.swing.JCheckBox();
        backJButton = new javax.swing.JButton();
        messageJTextField = new javax.swing.JTextField();
        requestTestJButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        messageJTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 24)); // NOI18N
        jLabel2.setText("Message");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 120, 40));

        jLabel3.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 24)); // NOI18N
        jLabel3.setText("Blood");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 120, 40));

        rbcCheckBox.setBackground(new java.awt.Color(51, 255, 102));
        rbcCheckBox.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        rbcCheckBox.setText("RBC");
        add(rbcCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 150, 50));

        glCheckBox.setBackground(new java.awt.Color(51, 255, 102));
        glCheckBox.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        glCheckBox.setText("Glucose");
        add(glCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, 150, 50));

        triCheckBox.setBackground(new java.awt.Color(51, 255, 102));
        triCheckBox.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        triCheckBox.setText("Triglycerides");
        add(triCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 320, 160, 50));

        jLabel4.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 24)); // NOI18N
        jLabel4.setText("Urine");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 120, 40));

        proCheckBox.setBackground(new java.awt.Color(51, 255, 102));
        proCheckBox.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        proCheckBox.setText("Protein");
        add(proCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 150, 50));

        choCheckBox.setBackground(new java.awt.Color(51, 255, 102));
        choCheckBox.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        choCheckBox.setText("Cholesterol");
        add(choCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 380, 150, 50));

        sugarCheckBox.setBackground(new java.awt.Color(51, 255, 102));
        sugarCheckBox.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        sugarCheckBox.setText("Sugar");
        add(sugarCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 380, 160, 50));

        jLabel5.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 24)); // NOI18N
        jLabel5.setText("Stool");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 120, 40));

        diaCheckBox.setBackground(new java.awt.Color(51, 255, 102));
        diaCheckBox.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        diaCheckBox.setText("Diarrhoea");
        add(diaCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 150, 50));

        nauCheckBox.setBackground(new java.awt.Color(51, 255, 102));
        nauCheckBox.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        nauCheckBox.setText("Nausea");
        add(nauCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 440, 150, 50));

        fatCheckBox.setBackground(new java.awt.Color(51, 255, 102));
        fatCheckBox.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        fatCheckBox.setText("Fatigue");
        add(fatCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 440, 160, 50));

        backJButton.setBackground(new java.awt.Color(0, 102, 102));
        backJButton.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 24)); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 760, 300, 60));

        messageJTextField.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 24)); // NOI18N
        add(messageJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 270, 50));

        requestTestJButton.setBackground(new java.awt.Color(51, 255, 102));
        requestTestJButton.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 24)); // NOI18N
        requestTestJButton.setText("Request Test");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });
        add(requestTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 760, 300, 60));

        jLabel6.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 24)); // NOI18N
        jLabel6.setText("Message");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 120, 40));

        messageJTextField1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        add(messageJTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 270, 50));

        jLabel11.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 40)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Request To Lab");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 470, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/dhcs/util/image/requestToLab.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1700, 1000));
    }// </editor-fold>//GEN-END:initComponents

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed
        
        String message = messageJTextField.getText();
        if(!message.trim().isEmpty()){
                Map<String, Boolean> booleanMap = new HashMap<String, Boolean>();
                booleanMap.put(rbcCheckBox.getText(), rbcCheckBox.isSelected());
                booleanMap.put(glCheckBox.getText(), glCheckBox.isSelected());
                booleanMap.put(triCheckBox.getText(), triCheckBox.isSelected());
                booleanMap.put(proCheckBox.getText(), proCheckBox.isSelected());
                booleanMap.put(choCheckBox.getText(), choCheckBox.isSelected());
                booleanMap.put(sugarCheckBox.getText(), sugarCheckBox.isSelected());
                booleanMap.put(diaCheckBox.getText(), diaCheckBox.isSelected());
                booleanMap.put(nauCheckBox.getText(), nauCheckBox.isSelected());
                booleanMap.put(fatCheckBox.getText(), fatCheckBox.isSelected());
                LabTestWorkRequest request = new LabTestWorkRequest();
                request.setMessage(message);
                request.setSender(userAccount);
                request.setBooleanMap(booleanMap);
                request.setStatus("Sent");

                
                Organization org = null;
                for (Organization organization : ((Doctor)userAccount.getEmployee()).getHospitalEnterprise()
                        .getOrganizationDirectory().getOrganizationList()){

                    if (organization instanceof LabOrganization){
                        org = organization;
                        break;
                    }
                }
                if (org!=null){
                    org.getWorkQueue().getWorkRequestList().add(request);
                    userAccount.getWorkQueue().getWorkRequestList().add(request);
                }
                JOptionPane.showMessageDialog(this, "Request sent to laboratory successfully",
                    "Decentralised Health Care System",JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this, "Please pass a valid request message to lab",
                    "Decentralised Health Care System",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DoctorWorkAreaJPanel dwjp = (DoctorWorkAreaJPanel) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JCheckBox choCheckBox;
    private javax.swing.JCheckBox diaCheckBox;
    private javax.swing.JCheckBox fatCheckBox;
    private javax.swing.JCheckBox glCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField messageJTextField;
    private javax.swing.JTextField messageJTextField1;
    private javax.swing.JCheckBox nauCheckBox;
    private javax.swing.JCheckBox proCheckBox;
    private javax.swing.JCheckBox rbcCheckBox;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JCheckBox sugarCheckBox;
    private javax.swing.JCheckBox triCheckBox;
    // End of variables declaration//GEN-END:variables
}
